-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["MethylTiles_01_10"] = {{ name = "other", tiles = {"MethylTiles_01_5", "MethylTiles_01_3"} }, { name = "other", tiles = {"MethylTiles_01_5", "MethylTiles_01_3"} }}
overlayMap["MethylTiles_01_11"] = {{ name = "other", tiles = {"MethylTiles_01_20", "MethylTiles_01_19"} }, { name = "other", tiles = {"MethylTiles_01_20", "MethylTiles_01_19"} }}
overlayMap["MethylTiles_01_12"] = {{ name = "other", tiles = {"MethylTiles_01_1", "MethylTiles_01_18"} }, { name = "other", tiles = {"MethylTiles_01_1", "MethylTiles_01_18"} }}
overlayMap["MethylTiles_01_13"] = {{ name = "other", tiles = {"MethylTiles_01_4", "MethylTiles_01_2"} }, { name = "other", tiles = {"MethylTiles_01_4", "MethylTiles_01_2"} }}
overlayMap["Onitiles_50"] = {{ name = "other", tiles = {"Onitiles_54", "Onitiles_52"} }, { name = "other", tiles = {"Onitiles_54", "Onitiles_52"} }}
overlayMap["Onitiles_51"] = {{ name = "other", tiles = {"Onitiles_55", "Onitiles_53"} }, { name = "other", tiles = {"Onitiles_55", "Onitiles_53"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
